name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        blender-version: ['4.2', '4.3', '4.4', '4.5']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Sync dependencies
        run: uv sync

      - name: Run tests with Blender ${{ matrix.blender-version }}
        run: uv run --with "bpy==${{ matrix.blender-version }}.*,numpy<2.0" main.py
